apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${namespace}
  name: ${micro_service_name}-${version_switch}
  labels:
    app: ${micro_service_name}
    version: ${version_switch}
spec:
  replicas: ${replicas_count}
  selector:
    matchLabels:
      app: ${micro_service_name}
  template:
    metadata:
      labels:
        app: ${micro_service_name}
        version: ${version_switch}
    spec:
      containers:
        - env:
            - name: version_switch
              value: ${version_switch}
            - name: TZ
              value: Asia/Shanghai
          name: ${micro_service_name}-${version_switch}
          image: ${image_repo}
          resources:
            requests:
              cpu: ${requests_cpu}
              memory: ${requests_memory}
              ephemeral-storage: 2Gi
            limits:
              cpu: ${limits_cpu}
              memory: ${limits_memory}
              ephemeral-storage: 2Gi
      imagePullSecrets:
        - name: ${imagePullSecret}
---
apiVersion: v1
kind: Service
metadata:
  name: ${micro_service_name}-svc
  namespace: ${namespace}
  labels:
    app: ${micro_service_name}-svc
spec:
  selector:
    app: ${micro_service_name}
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${micro_service_name}-${version_switch}-hpa
  namespace: ${namespace}
  labels:
    app: ${micro_service_name}-${version_switch}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${micro_service_name}-${version_switch}
  minReplicas: ${min_replica}
  maxReplicas: ${max_replica}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
